### ISSUE TITLE
Broken links in home page

### ISSUE THREAD

**Issue by jtmiclat** [geoparquet/geoparquet.github.io#17]
**Describe the bug**
The following links are broken in the home page https://geoparquet.org/ as they point to 404 pages
- References to the GPQ library: https://github.com/tschaub/gpq
- References to Sedona: https://sedona.apache.org/tutorial/sql/#load-geoparquet

I think the new url for Sedona should be 
https://sedona.apache.org/latest-snapshot/tutorial/sql/#load-geoparquet

**Comment by tschaub** [comment]
Thanks for the report.  I think these links have been removed or corrected.  Please reopen if you find other 404s.
